config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates_presence_of :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :user_name, presence: true, length: {minimum: 4, maximum: 16 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html {redirect_to root_path, notice: 'Your comment was saved!' }
        format.js
      else
        format.html {render root_pather, notice: 'Check the comment form, something went wrong.'}
        format.js
      end
    end
  end

  format.html { redirect_to @post, notice: 'Post was successfully created.' }
  format.json { render :show, status: :created, location: @post }
else
  format.html { render :new }
  format.json { render json: @post.errors, status: :unprocessable_entity }
end

  def destroy
    @comment = @post.comments.find(params[:id])

    respond_to do |format|
      if @comment.user_id == current_user.id
        @comment.delete
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owned_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # @comments = Comment.where(post_id: @post).order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :caption)
    end

    # Use to protect users posts
    def owned_post
      unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
      end
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="user-name">
  <%= comment.user.user_name %>
</div>
<div class="comment-content">
    <%= comment.content %>
</div>
  <% if comment.user == current_user %>
      <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are You Sure?"}, remote: true do %>
        <span class="glyphicon glyphicon-remove delete-comment"></span>
      <% end %>
  <% end %>

app/views/comments/_form.html.erb
<div class="posts-wrapper">
    <div class="post">
      <div class="post-head">
        <div class="thumb-img"></div>
        <div class="user-name"><%= post.user.user_name %></div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url, class: 'img-responsive'), post_path(post)%>
      </div>

      <div class="post-bottom">
        <div class="caption">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
          <%= post.caption %>
        </div>
        <% if post.comments %>
          <% post.comments.each do |comment| %>
            <div class="comment">
              <div class="user-name">
                <%= comment.user.user_name %>
              </div>
              <div class="comment-content">
                <%= comment.content %>
              </div>
              <% if comment.user == current_user %>
                <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div><!-- post bottom-->

        <div class="comment-form">
          <%= form_for [post, post.comments.build] do |f| %>
              <%= f.text_field :content, placeholder: 'Add a comment ...' %>
          <% end %>
        </div>

    </div><!--end post div-->
</div><!--end wrapper div-->

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-option-vertical"></span>
      </button>
      <%= link_to (root_path), :class => 'name navbar-brand' do %>
        <span>DevGram</span>
      <% end %>
    </div>
    <div id="navbar" class="collapse navbar-collapse pull-right">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <%  end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>DevGram</title>
    <%= csrf_meta_tags %>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,700|Raleway:100,300,700" rel="stylesheet">
    <!-- Fontawesome for Icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive' %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.profile_size.url, class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
        <div class="time-ago">
          <%= time_ago_in_words post.created_at %>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for [post, post.comments.build], remote: true do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = post.user.user_name
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      .caption
        .user-name
          = post.user.user_name
        = post.caption
      - if post.comments
        - post.comments.each do |comment|
          .comment
            .user-name
              = comment.user.user_name
            .comment-content
              = comment.content
            - if comment.user == current_user
              = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do
                %span(class="glyphicon glyphicon-remove delete-comment")
    .comment-like-form.row
      .like-button.col-sm-1
        %span(class="glyphicon glyphicon-heart-empty")
      .comment-form.col-sm-11
        = form_for [post, post.comments.new] do |f|
          = f.text_field :content, placeholder: 'Add a comment...'

app/views/posts/edit.html.erb
<div id="starter" class="container">
  <h1 class="text-center">Editing Post</h1>

  <%= render 'form' %>

  <div class="text-center edit-links">
    <%= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <%= link_to 'Cancel', posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div id="starter" class="container">
  <% @posts.each do |post| %>
    <div class="posts-wrapper row">
        <div class="post">
          <div class="post-head">
            <div class="name"><%= post.user.user_name %></div>
          </div>
          <div class="image center-block">
            <%= link_to (image_tag post.image.full_size.url, class:'img-responsive'), post_path(post) %>
          </div>
        </div>


    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div id="starter" class="container">
  <div class="row">
      <h1 class="text-center">New Post</h1>

      <%= render 'form', post: @post %>

      <%= link_to 'Back', posts_path %>
  </div>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="starter" class="container">
  <%= render 'post', post: @post %>

  <% if @post.user.id == current_user.id %>
    <div class="text-center edit-links">
      <%= link_to 'Cancel', posts_path %> |
      <%= link_to 'Edit', edit_post_path(@post) %>
    </div>
  <% else %>
    <div class="text-center edit-links">
      <%= link_to 'Cancel', posts_path %>
    </div>
  <% end %>




</div>